export const TabOpened = "TabOpened"
export const OrderPlaced = "OrderPlaced"
export const FoodPrepared = "FoodPrepared"
export const FoodServed = "FoodServed"
export const DrinksServed = "DrinksServed"
export const TabClosed = "TabClosed"